class Tumor {
  String tumorName;
  String tumorDes;

  Tumor({
    required this.tumorName,
    required this.tumorDes,
  });
}

List<Tumor> tumors = [
  Tumor(
    tumorName: 'Neurocitoma',
    tumorDes:
        'Neurocytoma is a type of brain tumor that typically arises from cells called oligodendrocytes \or neurons, which are part of the central nervous system.\n 1) Origin- Neurocytomas usually develop within the ventricular system of the brain, particularly in the lateral ventricles. However, they can also occur in other regions of the brain, such as the cerebral cortex or cerebellum.\n 2) Symptoms- The symptoms of neurocytomas can vary depending on their size and location within the brain. Common symptoms may include headaches, seizures, changes in vision or hearing, nausea, vomiting, and neurological deficits such as weakness or numbness in the limbs.\n 3)Diagnosis: Diagnosis of neurocytoma typically involves a combination of imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans, which can help identify the location, size, and characteristics of the tumor. A biopsy may also be performed to confirm the diagnosis by examining the tumor cells under a microscope.\n 4)Treatment: The treatment approach for neurocytoma depends on various factors including the tumor size, location, grade, and the patient\'s overall health. Treatment options may include surgical resection to remove the tumor, radiation therapy, chemotherapy, or a combination of these therapies. In some cases, particularly for small, asymptomatic tumors, close monitoring without immediate treatment may be recommended.',
  ),
  Tumor(
    tumorName: 'Tuberculoma',
    tumorDes:
        'Tuberculoma is a type of brain tumor caused by tuberculosis (TB) infection. Unlike other brain tumors that arise from abnormal growth of cells within the brain, tuberculomas result from the body\'s immune response to TB bacteria.\n1)Cause: Tuberculomas develop when Mycobacterium tuberculosis, the bacteria that cause tuberculosis, infect the brain. The immune system reacts to the presence of the bacteria by forming granulomas, which are small, organized collections of immune cells. These granulomas can form in various organs, including the brain, and are called tuberculomas when they occur in the brain.\n 2)Symptoms: The symptoms of tuberculoma can vary depending on the size, location, and number of lesions in the brain. Common symptoms may include headache, seizures, focal neurological deficits such as weakness or numbness, altered mental status, and signs of increased intracranial pressure such as nausea, vomiting, and papilledema (swelling of the optic disc).\n 3)Diagnosis: Diagnosis of tuberculoma typically involves a combination of medical history, clinical evaluation, imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans of the brain, and sometimes laboratory tests such as cerebrospinal fluid analysis or TB skin tests. Imaging studies can help identify characteristic features of tuberculomas, such as multiple ring-enhancing lesions with surrounding edema.\n 4)Treatment: Treatment of tuberculoma involves a combination of anti-tuberculosis medications (such as isoniazid, rifampin, pyrazinamide, and ethambutol) to eliminate the TB bacteria and reduce inflammation in the brain. In some cases, surgical intervention may be necessary to drain abscesses or remove large lesions causing mass effect. Corticosteroids may also be prescribed to reduce inflammation and swelling in the brain.',
  ),
  Tumor(
    tumorName: 'Schwannoma',
    tumorDes:
        'Schwannomas, also known as neurilemmomas, are benign tumors that arise from Schwann cells, which are the cells that produce the myelin sheath covering peripheral nerves. While they most commonly occur in the head and neck region, including the vestibular nerve (acoustic neuroma), schwannomas can also develop in the brain, particularly along cranial nerves.\n 1)Origin: Schwannomas originate from Schwann cells, which are responsible for the myelination (insulation) of peripheral nerves. \n 2)Symptoms: The symptoms of brain schwannomas depend on their location and size. Common symptoms may include hearing loss, tinnitus (ringing in the ears), vertigo, balance problems, facial numbness or weakness, headaches, visual disturbances, difficulty swallowing, and changes in speech. The symptoms may be gradual and progressive as the tumor grows and compresses surrounding structures.\n 3)Diagnosis: Diagnosis of brain schwannoma typically involves a combination of medical history, neurological examination, and imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans. These imaging techniques can help visualize the tumor, its location, size, and relationship to adjacent structures. \n 4)Treatment: Treatment options for brain schwannomas depend on factors such as tumor size, location, symptoms, and the patient\'s overall health. Small, asymptomatic tumors may be monitored closely with periodic imaging to track any changes in size or symptoms',
  ),
  Tumor(
    tumorName: 'Meningioma',
    tumorDes:
        'Meningiomas are tumors that arise from the meninges, which are the protective layers of tissue that cover the brain and spinal cord. These tumors are typically slow-growing and are often benign (non-cancerous), although in rare cases they can be malignant (cancerous). Meningiomas are the most common type of primary brain tumor, accounting for about 30% of all brain tumors.\n 1) Origin: Meningiomas develop from the arachnoid cells of the meninges, which are one of the three layers of tissue that surround and protect the brain and spinal cord. \n 2)Symptoms: The symptoms of meningiomas vary depending on their size, location, and rate of growth. Common symptoms may include headaches, seizures, focal neurological deficits such as weakness or sensory changes, visual disturbances, cognitive changes, and symptoms related to increased intracranial pressure such as nausea, vomiting, and papilledema (swelling of the optic disc).\n 3)Diagnosis: Diagnosis of meningioma typically involves a combination of medical history, neurological examination, and imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans. These imaging techniques can help visualize the tumor, its location, size, and relationship to adjacent structures. \n 4)Treatment: Treatment options for meningiomas depend on factors such as tumor size, location, symptoms, and the patient\'s overall health. Small, asymptomatic tumors may be monitored closely with periodic imaging to track any changes in size or symptoms. Surgical resection is often recommended for larger or symptomatic tumors, aiming to remove as much of the tumor as possible while preserving neurological function. In cases where surgery is not feasible or the tumor is inoperable, other treatment modalities such as stereotactic radiosurgery or radiation therapy may be considered to control tumor growth and alleviate symptoms.',
  ),
  Tumor(
    tumorName: 'Oligodendroglioma',
    tumorDes:
        'Oligodendroglioma is a type of primary brain tumor that arises from oligodendrocytes, which are a type of glial cell responsible for producing the myelin sheath that surrounds nerve fibers in the central nervous system. These tumors are typically slow-growing and are classified as low-grade (grade II) or high-grade (grade III) based on their cellular characteristics and aggressiveness.oligodendrogliomas.\n 1)Origin: Oligodendrogliomas originate from oligodendrocytes, which are specialized glial cells found in the central nervous system. These tumors typically arise in the cerebral hemispheres of the brain, particularly in the frontal and temporal lobes, but they can occur in other regions as well.\n 2)Symptoms: The symptoms of oligodendrogliomas depend on their location within the brain and the extent of their growth. Common symptoms may include seizures (which are often the initial presenting symptom), headaches, cognitive changes, weakness or numbness in the limbs, visual disturbances, and other neurological deficits.\n 3)Diagnosis: Diagnosis of oligodendroglioma typically involves a combination of medical history, neurological examination, and imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans. These imaging techniques can help visualize the tumor, its location, size, and characteristics. \n 4)Treatment: Treatment options for oligodendrogliomas depend on factors such as tumor grade, size, location, and the patient\'s overall health. For low-grade oligodendrogliomas, the primary treatment is typically surgical resection to remove as much of the tumor as possible, followed by close monitoring with periodic imaging and possibly adjuvant therapy such as radiation or chemotherapy. ',
  ),
  Tumor(
    tumorName: 'Meduloblastoma',
    tumorDes:
        'Medulloblastoma is a highly malignant type of brain tumor that predominantly affects children and adolescents, although it can also occur in adults. It arises in the cerebellum, which is located at the back of the brain, and typically grows rapidly.\n 1)Origin: Medulloblastomas arise from primitive or embryonic cells in the cerebellum called neuroectodermal cells. These cells are involved in the development of the central nervous system during early embryonic stages.\n 2)Symptoms: The symptoms of medulloblastoma often include headaches, nausea, vomiting (particularly in the morning), unsteadiness or difficulty walking (ataxia), problems with coordination, visual disturbances, and behavioral changes. In children, symptoms may also include irritability, lethargy, and developmental delays.\n 3)Diagnosis: Diagnosis of medulloblastoma typically involves a combination of medical history, neurological examination, and imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans. These imaging techniques can help visualize the tumor, its location, size, and characteristics. \n 4)Treatment: Treatment for medulloblastoma usually involves a combination of surgery, radiation therapy, and chemotherapy. Surgical resection aims to remove as much of the tumor as possible without causing significant neurological deficits.',
  ),
  Tumor(
    tumorName: 'Granuloma',
    tumorDes:
        'Granulomas in the brain are rare and can occur due to various underlying causes. A granuloma is a mass of immune cells that forms when the immune system attempts to isolate and contain foreign substances such as bacteria, fungi, parasites, or inert materials. In the brain, granulomas can result from infections, inflammatory conditions, or reactions to foreign bodies. \n 1)Causes: Brain granulomas can be caused by infectious agents such as bacteria (e.g., tuberculosis, syphilis, toxoplasmosis), fungi (e.g., cryptococcosis, aspergillosis), parasites (e.g., cysticercosis, toxocariasis), or viruses (e.g., cytomegalovirus). They can also occur in response to non-infectious inflammatory conditions such as sarcoidosis or Wegener\'s granulomatosis, or as a reaction to foreign bodies such as surgical materials or certain medications.\n2)Symptoms: The symptoms of brain granulomas can vary depending on their size, location, and underlying cause. Common symptoms may include headaches, seizures, focal neurological deficits such as weakness or sensory changes, cognitive changes, visual disturbances, and signs of increased intracranial pressure such as nausea, vomiting, and papilledema (swelling of the optic disc).\n3)Diagnosis: Diagnosis of brain granulomas typically involves a combination of medical history, neurological examination, imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans, and sometimes laboratory tests such as cerebrospinal fluid analysis or serological testing for specific infectious agents. \n4)Treatment: Treatment of brain granulomas depends on the underlying cause. Infectious granulomas may require antimicrobial therapy with antibiotics, antifungal agents, or antiparasitic drugs, depending on the specific organism involved.',
  ),
  Tumor(
    tumorName: 'Glioblastoma',
    tumorDes:
        'Glioblastoma, also known as glioblastoma multiforme (GBM), is the most aggressive and malignant type of primary brain tumor in adults.\n 1)Origin: Glioblastomas arise from glial cells, which are supportive cells in the brain. Specifically, they develop from astrocytes, a type of glial cell responsible for providing nutrients to neurons and maintaining the blood-brain barrier.\n 2)Symptoms: The symptoms of glioblastoma can vary depending on the tumor\'s location within the brain. Common symptoms may include headaches, seizures, focal neurological deficits such as weakness or sensory changes, cognitive changes, visual disturbances, and signs of increased intracranial pressure such as nausea, vomiting, and papilledema (swelling of the optic disc).\n 3)Diagnosis: Diagnosis of glioblastoma typically involves a combination of medical history, neurological examination, and imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans. These imaging techniques can help visualize the tumor, its location, size, and characteristics. A biopsy may also be performed to confirm the diagnosis by examining the tumor tissue under a microscope.\n 4)Treatment: Treatment for glioblastoma usually involves a combination of surgery, radiation therapy, and chemotherapy. Surgical resection aims to remove as much of the tumor as possible without causing significant neurological deficits. Radiation therapy is typically administered to the tumor bed and surrounding brain tissue to target any remaining cancer cells. Chemotherapy may be given before or after surgery, or both, to further shrink the tumor and kill cancer cells.',
  ),
  Tumor(
    tumorName: 'Germinoma',
    tumorDes:
        'Germinomas are a type of brain tumor that primarily affects the pineal gland and the suprasellar region of the brain. These tumors are part of a group of tumors called germ cell tumors, which arise from primordial germ cells that are normally present in the developing embryo. \n 1)Origin: Germinomas originate from germ cells, which are cells that give rise to sperm and eggs. During embryonic development, some germ cells migrate to the brain and other locations in the body. Germinomas arise from these migrated germ cells when they fail to differentiate into their mature forms and instead proliferate uncontrollably.\n 2)Symptoms: The symptoms of germinomas depend on their location within the brain and the extent of their growth. Common symptoms may include headaches, nausea, vomiting, visual disturbances, hormonal imbalances, changes in mood or behavior, and signs of increased intracranial pressure such as papilledema (swelling of the optic disc).\n 3)Diagnosis: Diagnosis of germinoma typically involves a combination of medical history, neurological examination, and imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans. These imaging techniques can help visualize the tumor, its location, size, and characteristics. A biopsy may also be performed to confirm the diagnosis by examining the tumor tissue under a microscope.\n 4)Treatment: Treatment for germinoma usually involves a combination of surgery, radiation therapy, and chemotherapy. Surgical resection may be performed to obtain a tissue sample for diagnosis or to relieve symptoms caused by the tumor\'s mass effect. Radiation therapy is typically administered to the tumor bed and surrounding brain tissue to target any remaining cancer cells. ',
  ),
  Tumor(
    tumorName: 'Carcinoma',
    tumorDes:
        'Carcinomas are a type of malignant tumor that typically arise from epithelial cells, which are the cells that line the surfaces and cavities of the body. While carcinomas are more commonly associated with cancers of organs such as the skin, lungs, breast, prostate, and colon, they can also occur in the brain. However, primary brain carcinomas are relatively rare compared to other types of brain tumors. \n1)Origin: Brain carcinomas originate from epithelial cells that line the structures within the brain, such as the lining of the ventricles or the meninges (the protective layers covering the brain and spinal cord). \n 2)Symptoms: The symptoms of brain carcinomas can vary depending on their location within the brain and the extent of their growth. Common symptoms may include headaches, seizures, focal neurological deficits such as weakness or sensory changes, cognitive changes, visual disturbances, and signs of increased intracranial pressure such as nausea, vomiting, and papilledema (swelling of the optic disc).\n3)Diagnosis: Diagnosis of brain carcinomas typically involves a combination of medical history, neurological examination, and imaging studies such as MRI (Magnetic Resonance Imaging) or CT (Computed Tomography) scans. These imaging techniques can help visualize the tumor, its location, size, and characteristics. \n4)Treatment: Treatment for brain carcinomas usually involves a combination of surgery, radiation therapy, and chemotherapy. Surgical resection aims to remove as much of the tumor as possible without causing significant neurological deficits. Radiation therapy is typically administered to the tumor bed and surrounding brain tissue to target any remaining cancer cells.',
  ),
  Tumor(
    tumorName: 'Astrocitoma',
    tumorDes:
        '1)Origin:  astrocytes are a type of glial cell in the brain. Glial cells provide support and nourishment to neurons and help maintain the brain\s environment. However, when these cells undergo abnormal growth and division, they can form tumors known as astrocytomas.\n2)Symptoms:  Headaches, often worsening in the morning or with changes in position.Seizures, which can be focal (affecting one part of the body) or generalized.Cognitive changes, including memory problems, difficulty concentrating, or changes in behavior.Motor deficits, such as weakness, clumsiness, or difficulty walking.Visual disturbances, including blurry vision or loss of vision.Nausea and vomiting, particularly if the tumor is causing increased pressure within the skull.\n3)Diagnosis: Diagnosis of astrocytomas typically involves several steps:Neurological examination: This includes assessing the patient\'s cognitive function, motor skills, reflexes, and sensory function.Imaging studies: MRI (magnetic resonance imaging) or CT (computed tomography) scans are used to visualize the brain and identify any abnormalities, such as tumors. These scans can help determine the location, size, and characteristics of the tumor.Biopsy: In some cases, a biopsy may be performed to obtain a tissue sample from the tumor for histological examination. This helps determine the tumor\'s grade and other characteristics, which are important for treatment planning.\n4)Treatment: Treatment for astrocytomas depends on factors such as the tumor grade, size, location, and the patient\'s overall health. Options may include:Surgery: Surgical resection is often the first-line treatment for astrocytomas, particularly for low-grade tumors. The goal is to remove as much of the tumor as safely possible while preserving neurological function.Radiation therapy: Radiation therapy may be used before or after surgery to target any remaining tumor cells and reduce the risk of recurrence. It may also be used as the primary treatment for tumors that cannot be surgically removed.Chemotherapy: Chemotherapy may be used alone or in combination with surgery and/or radiation therapy, particularly for high-grade astrocytomas such as glioblastomas. ',
  ),
];
